version: '3.3'

services:
  auth:
    restart: always
    build:
      context: ../../..
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8090:8090
    environment:
      MODE: development
      # PORT: 80
      # SERVER_NAME: localhost
      # CLIENT_MAX_BODY_SIZE: 1m 
      # PROXY_READ_TIMEOUT: 60s
      # WORKER_PROCESSES: auto
      PROXY_PASS: http://web:8080
      ROOT_URL: http://127.0.0.1:8080
      PROVIDER: auth0
      CLIENT_ID: d6de1ENMGne8K23M48eIZhL5qfHGz0x6
      CLIENT_SECRET: CHANGE_CLIENT_SECRET
      # REDIRECT_URI: http://127.0.0.1:8080/login/coding/callback
      # SCOPE: 'user'
      # #
      # AUTHORIZE_URL: https://whatwewant.coding.net/oauth_authorize.html
      # TOKEN_URL: https://whatwewant.coding.net/api/oauth/access_token
      # USER_INFO_URL: https://whatwewant.coding.net/api/account/current_user
      # #
      # TOKEN_DATA_IN_QUERY: 1
      # #
      # USER_INFO_QUERY: access_token
      # #
      # USER_USERNAME: data.global_key
      # USER_NICKNAME: data.name
      # # USER_EMAIL: data.email
      # USER_AVATAR: data.avatar
      # 
      ALLOW_USERNAMES: tobewhatwewant@outlook.com
      # Cookie Secret
      COOKIE_SECRET: whatwewant
    volumes:
      - ../../../packages:/usr/local/openresty/lualib/oauth

  web:
    image: nginx:1.17.2-alpine
    # ports:
    #   - 8080:8080
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/html:/var/www/html

# docker-composee up
# docker-compose exec auth sh