version: '3.7'

services:
  guard:
    restart: always
    build:
      context: ../../..
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8090:8090
    # env_file: .env
    environment:
      MODE: development
      # PORT: 80
      # SERVER_NAME: localhost
      # CLIENT_MAX_BODY_SIZE: 1m 
      # PROXY_READ_TIMEOUT: 60s
      # WORKER_PROCESSES: auto
      PROXY_PASS: http://web:8080
      #
      ROOT_URL: http://127.0.0.1:8080
      PROVIDER: doreamon
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      # REDIRECT_URI: http://127.0.0.1:8080/login/github/callback
      SCOPE: user
      #
      # AUTHORIZE_URL: https://github.com/login/oauth/authorize
      # TOKEN_URL: https://github.com/login/oauth/access_token
      # USER_INFO_URL: https://api.github.com/user
      # #
      # TOKEN_DATA_IN_BODY: 1
      # #
      # USER_INFO_HEADER: 'Authorization'
      # #
      # USER_USERNAME: login
      # USER_NICKNAME: name
      # USER_EMAIL: email
      # USER_AVATAR: avatar_url
      # 
      ALLOW_USERNAMES: tobewhatwewant@gmail.com
      # Cookie Secret
      COOKIE_SECRET: whatwewant
    volumes:
      - ../../../packages:/usr/local/openresty/lualib/oauth

  web:
    image: nginx:1.17.2-alpine
    # ports:
    #   - 8080:8080
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/html:/var/www/html

# docker-composee up
# docker-compose exec auth sh